src/catalog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('catalog.views',
    url(r'^$', 'index', name='catalog_index'),
    url(r'^add/$', 'add', name='catalog_add'),
    url(r'^(?P<item_id>\d+)/$', 'view', name='catalog_view'),
    url(r'^(?P<item_id>\d+)/feedback/$', 'feedback', name='catalog_feedback'),
    url(r'^(?P<item_id>\d+)/edit/(?P<secret_key>.+)/$', 'edit', name='catalog_edit'),
    url(r'^(?P<item_id>\d+)/delete/(?P<secret_key>.+)/$', 'delete', name='catalog_delete'),
)

src/main/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from catalog.feeds import LatestEntriesFeed

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'catalog.views.index', name='home'),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^subscription/', include('subscription.urls')),
    url(r'^feedback/', include('feedback.urls')),
    url(r'^feed/$', LatestEntriesFeed()),
    url(r'^admin/', include(admin.site.urls)),
)

src/catalog/models.py
#coding=utf8
from datetime import datetime
from django.contrib.sites.models import Site
from django.core.mail import EmailMultiAlternatives

from django.db import models
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django_extensions.db.models import TimeStampedModel
from common.utils import make_uniq_key

class ActiveItemManager(models.Manager):
    def get_queryset(self):
        return super(ActiveItemManager, self).get_queryset().filter(is_active=True, site=Site.objects.get_current())


class Item(TimeStampedModel):
    title = models.CharField(u'Название', max_length=255, help_text=u'Краткое описание вакансии')
    description = models.TextField(u'Полное описание')
    email = models.EmailField(u'Контактный E-mail', help_text=u'Только для получения анкет, не публикуется на сайте')
    salary = models.CharField(u'Заработная плата', max_length=255, help_text=u'Фиксированная сумма или диапазон, может оставаться пустым, не забывайте указывать знак валюты - это важно! ')
    on_site = models.BooleanField(u'Это работа только в офисе', default=False)
    city = models.CharField(u'Город', max_length=255, blank=True, null=True, help_text=u'В каком городе находится офис')
    employer_name = models.CharField(u'Название', max_length=255, blank=True, null=True, help_text=u'Название вашей компании или стартапа')
    employer_description = models.TextField(u'Описание', blank=True, null=True, help_text=u'Ваше краткое описание')
    employer_website = models.URLField(u'Сайт', blank=True, null=True)
    secret_key = models.CharField(max_length=255, blank=True)
    not_sended = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    site = models.ForeignKey(Site)

    objects = models.Manager()
    active_objects = ActiveItemManager()


    def __unicode__(self):
        return self.title

    class Meta:
        pass

@receiver(pre_save, sender=Item)
def make_secret_key(sender, instance=None, **kwargs):
    if not instance.pk:
        instance.secret_key = make_uniq_key()[:4]

@receiver(post_save, sender=Item)
def send_info(sender, instance=None, created=False, **kwargs):
    if created:
        c = {
            'site': Site.objects.get_current(),
            'item': instance,
        }

        subject = render_to_string('catalog/email/item_subject.txt', c)
        html_body = render_to_string('catalog/email/item_body.html', c)
        text_body = strip_tags(html_body)

        msg = EmailMultiAlternatives(subject, text_body, None, instance.email.split(','))
        msg.attach_alternative(html_body, "text/html")
        msg.send()


class Application(TimeStampedModel):
    item = models.ForeignKey(Item)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    about = models.TextField(max_length=2048)

    def __unicode__(self):
        return self.name

    class Meta:
        pass


@receiver(post_save, sender=Application)
def send_application(sender, instance=None, created=False, **kwargs):
    if created:
        c = {
            'site': Site.objects.get_current(),
            'application': instance,
        }

        subject = render_to_string('catalog/email/application_subject.txt', c)
        html_body = render_to_string('catalog/email/application_body.html', c)
        text_body = strip_tags(html_body)

        msg = EmailMultiAlternatives(subject, text_body, instance.email, instance.item.email.split(','))
        msg.attach_alternative(html_body, "text/html")
        msg.send()

src/catalog/forms.py
from django import forms
from models import Item, Application
from nocaptcha_recaptcha import NoReCaptchaField


class AddItemForm(forms.ModelForm):
    # honeyspot
    country = forms.CharField(required=False)
    captcha = NoReCaptchaField()

    class Meta:
        model = Item
        exclude = ['secret_key', 'not_sended', 'is_active', 'site']


class ApplicationForm(forms.ModelForm):
    # honeyspot
    country = forms.CharField(required=False)

    class Meta:
        model = Application
        exclude = ['item',]

src/catalog/views.py
# coding=utf8
import json
from django.contrib import messages
from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseForbidden, HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from catalog.forms import AddItemForm, ApplicationForm
from catalog.models import Item


def index(request):
    items = Item.active_objects.all().order_by('-id')
    return render(request, 'catalog/index.html', {'items': items})


def view(request, item_id):
    item = get_object_or_404(Item.active_objects, pk=item_id)
    return render(request, 'catalog/view.html', {'item': item})

@csrf_exempt
@require_POST
def feedback(request, item_id):
    item = get_object_or_404(Item.active_objects, pk=item_id)

    form = ApplicationForm(request.POST)
    if form.is_valid():
        if not form.cleaned_data['country']:
            new_feedback = form.save(commit=False)
            new_feedback.item = item
            new_feedback.save()

        return HttpResponse(json.dumps({'success': True, 'message': 'Success'}), content_type="application/json")
    else:
        return HttpResponse(json.dumps({'success': False, 'errors': form.errors}), content_type="application/json")

def add(request):
    if request.method == 'POST':
        form = AddItemForm(request.POST)
        if form.is_valid():
            new_item = form.save(commit=False)
            new_item.site = Site.objects.get_current()
            new_item.save()
            messages.add_message(request, messages.SUCCESS,
                                 u'Ваше объявление успешно добавлено! Письмо со ссылкой для редактирования или удаления отправлена вам на email.')
            return HttpResponseRedirect(reverse('catalog_view', kwargs={'item_id': new_item.pk}))
        else:
            messages.add_message(request, messages.WARNING, u'Исправьте пожалуйста ошибки выделенные красным цветом')
    else:
        form = AddItemForm()

    return render(request, 'catalog/add.html', {'form': form})


def edit(request, item_id, secret_key):
    item = get_object_or_404(Item.active_objects, pk=item_id)

    if item.secret_key != secret_key:
        return HttpResponseForbidden('Forbidden')

    if request.method == 'POST':
        form = AddItemForm(request.POST, instance=item)
        if form.is_valid():
            new_item = form.save(commit=False)
            new_item.secret_key = item.secret_key
            new_item.save()

            messages.add_message(request, messages.SUCCESS,
                                 u'Ваше объявление успешно отредактировано!')
            return HttpResponseRedirect(
                reverse('catalog_edit', kwargs={'item_id': new_item.pk, 'secret_key': secret_key}))
        else:
            messages.add_message(request, messages.WARNING, u'Исправьте пожалуйста ошибки выделенные красным цветом')
    else:
        form = AddItemForm(instance=item)

    return render(request, 'catalog/edit.html', {'form': form, 'item': item})


def delete(request, item_id, secret_key):
    item = get_object_or_404(Item.active_objects, pk=item_id)

    if item.secret_key != secret_key:
        return HttpResponseForbidden('Forbidden')

    if request.method == 'POST':
        item.is_active = False
        item.save()
        messages.add_message(request, messages.SUCCESS, u'Ваше объявление успешно удалено!')
        return HttpResponseRedirect(reverse('catalog_index'))

    return render(request, 'catalog/delete.html', {'item': item})

src/catalog/templates/catalog/add.html
{% extends "base.html" %}

{% block js %}{{ block.super }}
    <script type="text/javascript">
        $(document).ready(function () {
            var dep_el = $('#id_city').parent();
            dep_el.hide();
            $('#id_on_site').change(function () {
                if (this.checked) {
                    dep_el.slideDown()
                } else {
                    dep_el.slideUp()
                }
            }).change();
        });
    </script>
{% endblock %}

{% block content %}
    <h2>Добавление новой вакансии</h2>

    <form action="." method="POST" class="form" role="form">{% csrf_token %}
        {% include 'common/elements/form_hidden_fields.html' %}
        {% include 'common/elements/form_errors.html' %}

        <br/>

        {% include 'common/elements/form_field.html' with item=form.title %}
        {% include 'common/elements/form_field.html' with item=form.description %}
        {% include 'common/elements/form_field.html' with item=form.email %}
        {% include 'common/elements/form_field.html' with item=form.salary %}
        {% include 'common/elements/form_field.html' with item=form.on_site %}
        {% include 'common/elements/form_field.html' with item=form.city %}

        <br/>
        <h3>О компании</h3>
        <hr/>

        {% include 'common/elements/form_field.html' with item=form.employer_name %}
        {% include 'common/elements/form_field.html' with item=form.employer_description %}
        {% include 'common/elements/form_field.html' with item=form.employer_website %}
        <hr/>
        {% include 'common/elements/form_field.html' with item=form.captcha %}

        <div class="form-group">
            <button type="submit" class="btn btn-primary col-group">Отправить</button>
        </div>

    </form>
{% endblock %}

src/catalog/templates/catalog/delete.html
{% extends "base.html" %}

{% block content %}
    <h2>{{ item.title }}</h2>

    <strong>Удалить вакансию?</strong>
    <form action="." method="POST" class="form" role="form">{% csrf_token %}
        <div class="form-group">
            <button type="submit" class="btn btn-danger col-group">Удалить</button>
        </div>

    </form>
{% endblock %}

src/catalog/templates/catalog/edit.html
{% extends "base.html" %}

{% block js %}{{ block.super }}
    <script type="text/javascript">
        $(document).ready(function () {
            var dep_el = $('#id_city').parent();
            dep_el.hide();
            $('#id_on_site').change(function () {
                if (this.checked) {
                    dep_el.slideDown()
                } else {
                    dep_el.slideUp()
                }
            }).change();
        });
    </script>
{% endblock %}

{% block content %}
    <h2>Редактирование вакансии</h2>

    <form action="." method="POST" class="form" role="form">{% csrf_token %}
        {% include 'common/elements/form_hidden_fields.html' %}
        {% include 'common/elements/form_errors.html' %}

        <br/>

        {% include 'common/elements/form_field.html' with item=form.title %}
        {% include 'common/elements/form_field.html' with item=form.description %}
        {% include 'common/elements/form_field.html' with item=form.email %}
        {% include 'common/elements/form_field.html' with item=form.salary %}
        {% include 'common/elements/form_field.html' with item=form.on_site %}
        {% include 'common/elements/form_field.html' with item=form.city %}

        <br/>
        <h3>О компании</h3>
        <hr/>

        {% include 'common/elements/form_field.html' with item=form.employer_name %}
        {% include 'common/elements/form_field.html' with item=form.employer_description %}
        {% include 'common/elements/form_field.html' with item=form.employer_website %}

        <div class="form-group">
            <button type="submit" class="btn btn-primary col-group">Отправить</button>
            <a class="btn btn-danger" href="{% url 'catalog_delete' item.id item.secret_key %}">Удалить</a>
        </div>

    </form>
{% endblock %}

src/catalog/templates/catalog/index.html
{% extends "base.html" %}

{% block content %}
    {% for i in items %}

            <div class="panel panel-success">
                 <div class="panel-heading">

                    <small>{{ i.created|date:"d.m.Y h:m:i" }}</small> |
                    {% if i.on_site %}
                        <span class="label label-success">Офис: {{ i.city }}</span>
                    {% else %}
                        <span class="label label-info">Удаленная работа</span>
                    {% endif %}
                    |
                    <span class="label label-warning">Оплата: {{ i.salary }}</span>

                  {% if i.employer_name %} |
                  {{ i.employer_name }}
                  {% endif %}

                 </div>

              <div class="panel-body">
                <h2><a href="{% url 'catalog_view' i.id %}">{{ i.title }}</a></h2>
                  {{ i.description|linebreaks|truncatewords_html:100 }}
              </div>

              <div class="panel-footer"><a class="btn btn-default" href="{% url 'catalog_view' i.id %}">Подробнее</a> </div>
            </div>

    {% endfor %}

    {% if not items %}
        <div class="well" style="text-align: center">Пока вакансий нет. Давайте подождем работодателей или посмотрим на других сайтах. <br/>Еще можно подписаться на новые вакансии кликнув на одноименную кнопку вверху страницы. Удачи!</div>
    {% endif %}

{% endblock %}

src/catalog/templates/catalog/view.html
{% extends "base.html" %}

{% block title %}{{ item.title }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-9">
        <h2>{{ item.title }}</h2>
        Добавлено: {{ item.created|date:"d.m.Y h:m:i" }} |
        {% if item.on_site %}
            <span class="label label-success">Офис: {{ item.city }}</span>
        {% else %}
            <span class="label label-info">Удаленная работа</span>
        {% endif %}

        <hr/>
        <h3>Описание</h3>
        {{ item.description|linebreaks }}

        {% if item.employer_description %}
        <hr/>
        <h4>О Компании</h4>
        {{ item.employer_description|linebreaks }}
        {% endif %}
    </div>

    <div class="col-lg-3">

        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Информация</h3>
          </div>
          <div class="panel-body">
              <dl>
                  <dt>Город</dt>
                  {% if item.on_site %}
                      <dd>{{ item.city }}</dd>
                  {% else %}
                      <dd>Удаленная</dd>
                  {% endif %}

                  {% if item.employer_name %}
                  <dt>Компания</dt>
                  <dd>{{ item.employer_name }}</dd>
                  {% endif %}

                  {% if item.employer_website %}
                  <dt>Сайт</dt>
                  <dd><a target="_blank" href="{{ item.employer_website }}">{{ item.employer_website }}</a></dd>
                  {% endif %}

                  <dt>Оплата</dt>
                  <dd>{{ item.salary }}</dd>
              </dl>

                <!-- Button trigger modal -->
                <button class="btn btn-success" data-toggle="modal" data-target="#feedback_dlg">
                  Откликнуться
                </button>


          </div>
        </div>

        <div class="sense sense-side">
            {% if site.name == 'djangojobbers.ru' %}
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                <!-- djangojobbers-sidebar -->
                <ins class="adsbygoogle"
                     style="display:inline-block;width:240px;height:400px"
                     data-ad-client="ca-pub-8893191334405901"
                     data-ad-slot="1519800940"></ins>
                <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            {% endif %}

            {% if site.name == 'phpjobbers.ru' %}
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                <!-- phpjobbers-sidebar -->
                <ins class="adsbygoogle"
                     style="display:inline-block;width:240px;height:400px"
                     data-ad-client="ca-pub-8893191334405901"
                     data-ad-slot="2996534147"></ins>
                <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            {% endif %}

        </div>

    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="feedback_dlg" tabindex="-1" role="dialog" aria-hidden="true" style="display: none">
    <div class="modal-dialog" data-ng-app="formApp"  data-ng-controller="formController" data-ng-init="init('{% url 'catalog_feedback' item.id %}')">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Отправить отклик на вакансию</h4>
            </div>

            <!-- FORM -->
            <form name="fb_form" data-ng-submit="processForm()">


            <div class="modal-body">
                    {% verbatim %}
                    <div id="name-group" class="form-group name_field" data-ng-class="{ 'has-error' : errorName }">
                        <label>Ваше имя</label>
                        <input type="text" name="name" class="form-control" placeholder="" data-ng-model="formData.name">
                        <span class="help-block" data-ng-show="errorName">{{ errorName.0 }}</span>
                    </div>

                    <div id="email-group" class="form-group email_field" data-ng-class="{ 'has-error' : errorEmail }">
                        <label>Email</label>
                        <input type="email" name="email" class="form-control" placeholder="" data-ng-model="formData.email">
                        <span class="help-block" data-ng-show="errorEmail">{{ errorEmail.0 }}</span>
                    </div>

                    <div id="feedback-group" class="form-group about_field" data-ng-class="{ 'has-error' : errorFeedback }">
                        <label>Информация о себе</label>
                        <textarea name="about" class="form-control"  data-ng-model="formData.about" rows="10"></textarea>
                        <span class="help-block" data-ng-show="errorAbout">{{ errorAbout.0 }}</span>
                    </div>

                    <div id="country-group" class="form-group country_field" data-ng-class="{ 'has-error' : errorCountry }">
                        <label>Страна</label>
                        <input type="text" name="country" class="form-control" placeholder="Например 'Россия'" data-ng-model="formData.country">
                        <span class="help-block" data-ng-show="errorCountry">{{ errorCountry.0 }}</span>
                    </div>

                    {% endverbatim %}

                    <input type="hidden" name="item_id" value="{{ item.id }}"/>



                <!-- SHOW DATA FROM INPUTS AS THEY ARE BEING TYPED -->
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                <button type="submit"  class="btn btn-primary">Отправить</button>
            </div>

            </form>
        </div>


    </div>

</div>

{% endblock %}

{% block js %}{{ block.super }}
    <script type="text/javascript">
        toastr.options = {
          "closeButton": true,
          "positionClass": "toast-top-full-width"
        }


		var formApp = angular.module('formApp', []);

        formApp.config(['$httpProvider', function ($httpProvider) {
            $httpProvider.defaults.xsrfCookieName = 'csrftoken';
            $httpProvider.defaults.xsrfHeaderName = 'X-CSRFToken';

        }]);

		formApp.controller('formController', function($scope, $http) {
            $scope.formData = {};

            $scope.init = function(url) {
                $scope.url = url;
            }

            $scope.processForm = function() {
                $http({
                    method  : 'POST',
                    url     : $scope.url,
                    data    : $.param($scope.formData),
                    headers : { 'Content-Type': 'application/x-www-form-urlencoded' }
                })
                    .success(function(data) {
                        console.log(data);

                        if (!data.success) {
                            // if not successful, bind errors to error variables
                            $scope.errorName = data.errors.name;
                            $scope.errorEmail = data.errors.email;
                            $scope.errorAbout = data.errors.about;
                        } else {
                            // if successful, bind success message to message
                            $scope.errorName = $scope.errorEmail = $scope.errorAbout = false;
                            $scope.message = data.message;

                            toastr.success('Ваш отклик был успешно отправлен!')
                            $('#feedback_dlg').modal('toggle');
                        }
                    });
            };


		})


    </script>
{% endblock %}